name: Auto Create File PRs

on:
  workflow_dispatch:
    inputs:
      create_prs:
        description: 'Create PRs for changed files'
        required: true
        default: true
        type: boolean
  
  # Optional: Run on push to main branch
  # push:
  #   branches: [ main ]

jobs:
  create-file-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Make script executable
        run: chmod +x create-file-prs.sh

      - name: Create PRs for changed files
        if: inputs.create_prs == true
        run: |
          # Run the script with automatic yes to prompts
          echo "y" | ./create-file-prs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## Auto File PR Creation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Script executed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- Check the PRs tab for newly created pull requests" >> $GITHUB_STEP_SUMMARY
          echo "- Each file change now has its own PR for individual testing" >> $GITHUB_STEP_SUMMARY 